"""stabilize reports and soft deletes

Revision ID: 021
Revises: 020
Create Date: 2026-07-12

"""
from alembic import op
import sqlalchemy as sa


revision = "021"
down_revision = "020"
branch_labels = None
depends_on = None


REPORT_INDEXES = {
    "ix_reports_id": ["id"],
    "ix_reports_reporter_id": ["reporter_id"],
    "ix_reports_reported_id": ["reported_id"],
    "ix_reports_status": ["status"],
    "ix_reports_created_at": ["created_at"],
    "ix_reports_target": ["reported_type", "reported_id"],
}


def _create_reports_table() -> None:
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reporter_id", sa.Integer(), nullable=False),
        sa.Column("reported_type", sa.String(), nullable=False),
        sa.Column("reported_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("reviewed_by_id", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["reporter_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["reviewed_by_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )


def _upgrade_postgresql() -> None:
    op.execute(
        sa.text(
            """
            CREATE TABLE IF NOT EXISTS reports (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                reporter_id INTEGER NOT NULL REFERENCES users(id),
                reported_type VARCHAR NOT NULL,
                reported_id INTEGER NOT NULL,
                reason VARCHAR NOT NULL,
                description TEXT,
                status VARCHAR NOT NULL,
                reviewed_by_id INTEGER REFERENCES users(id),
                reviewed_at TIMESTAMP WITH TIME ZONE,
                review_notes TEXT,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
            )
            """
        )
    )
    for name, columns in REPORT_INDEXES.items():
        op.execute(
            sa.text(
                f"CREATE INDEX IF NOT EXISTS {name} "
                f"ON reports ({', '.join(columns)})"
            )
        )
    op.execute(
        "UPDATE reports SET status = 'OPEN' WHERE status = 'PENDING'"
    )
    op.execute(
        "UPDATE reports SET status = 'UNDER_REVIEW' WHERE status = 'REVIEWED'"
    )
    op.execute("UPDATE reports SET reported_type = UPPER(reported_type)")
    op.execute("UPDATE reports SET reason = UPPER(reason)")
    op.execute(
        """
        UPDATE reports SET reason = CASE reason
            WHEN 'INAPPROPRIATE' THEN 'INAPPROPRIATE_CONTENT'
            WHEN 'FAKE' THEN 'FALSE_INFORMATION'
            WHEN 'SCAM' THEN 'FALSE_INFORMATION'
            ELSE reason END
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_reports_active_reporter_target
        ON reports (reporter_id, reported_type, reported_id)
        WHERE status IN ('OPEN', 'UNDER_REVIEW')
        """
    )

    for table in ("posts", "listings"):
        op.execute(
            sa.text(
                f"ALTER TABLE {table} "
                "ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE"
            )
        )
        op.execute(
            sa.text(
                f"CREATE INDEX IF NOT EXISTS ix_{table}_deleted_at "
                f"ON {table} (deleted_at)"
            )
        )


def _upgrade_other_dialects(bind) -> None:
    inspector = sa.inspect(bind)
    table_names = set(inspector.get_table_names())

    if "reports" not in table_names:
        _create_reports_table()
        report_indexes = set()
    else:
        report_indexes = {
            index["name"] for index in inspector.get_indexes("reports")
        }
    for name, columns in REPORT_INDEXES.items():
        if name not in report_indexes:
            op.create_index(name, "reports", columns)
    op.execute("UPDATE reports SET status = 'OPEN' WHERE status = 'PENDING'")
    op.execute(
        "UPDATE reports SET status = 'UNDER_REVIEW' WHERE status = 'REVIEWED'"
    )
    op.execute("UPDATE reports SET reported_type = UPPER(reported_type)")
    op.execute("UPDATE reports SET reason = UPPER(reason)")
    op.execute(
        """
        UPDATE reports SET reason = CASE reason
            WHEN 'INAPPROPRIATE' THEN 'INAPPROPRIATE_CONTENT'
            WHEN 'FAKE' THEN 'FALSE_INFORMATION'
            WHEN 'SCAM' THEN 'FALSE_INFORMATION'
            ELSE reason END
        """
    )
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_reports_active_reporter_target
        ON reports (reporter_id, reported_type, reported_id)
        WHERE status IN ('OPEN', 'UNDER_REVIEW')
        """
    )

    for table in ("posts", "listings"):
        column_names = {
            column["name"] for column in inspector.get_columns(table)
        }
        if "deleted_at" not in column_names:
            op.add_column(
                table,
                sa.Column(
                    "deleted_at",
                    sa.DateTime(timezone=True),
                    nullable=True,
                ),
            )
        index_names = {
            index["name"] for index in inspector.get_indexes(table)
        }
        index_name = f"ix_{table}_deleted_at"
        if index_name not in index_names:
            op.create_index(index_name, table, ["deleted_at"])


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        _upgrade_postgresql()
    else:
        _upgrade_other_dialects(bind)


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for table in ("listings", "posts"):
            op.execute(
                sa.text(f"DROP INDEX IF EXISTS ix_{table}_deleted_at")
            )
            op.execute(
                sa.text(
                    f"ALTER TABLE {table} DROP COLUMN IF EXISTS deleted_at"
                )
            )
        op.execute(sa.text("DROP TABLE IF EXISTS reports"))
        return

    inspector = sa.inspect(bind)
    table_names = set(inspector.get_table_names())
    for table in ("listings", "posts"):
        if table not in table_names:
            continue
        index_name = f"ix_{table}_deleted_at"
        index_names = {
            index["name"] for index in inspector.get_indexes(table)
        }
        if index_name in index_names:
            op.drop_index(index_name, table_name=table)
        column_names = {
            column["name"] for column in inspector.get_columns(table)
        }
        if "deleted_at" in column_names:
            op.drop_column(table, "deleted_at")
    if "reports" in table_names:
        op.drop_table("reports")
